### ISSUE TITLE
Edit in flag setting

### ISSUE THREAD

**Issue by fireballpoint1** [tdhock/PeakSegPipeline#4]
```
CPPFLAGS=-I${HOME}/include
LDFLAGS=-L${HOME}/lib -Wl,-rpath=${HOME}/lib
```
These commands should be written with quotes as : 

```
CPPFLAGS="-I${HOME}/include"
LDFLAGS="-L${HOME}/lib -Wl,-rpath=${HOME}/lib"
```
as the quotes should be compiled first and then fed into LDFLAGS

**Comment by tdhock** [comment]
on my system the quotes need to be ABSENT, see bottom of http://tdhock.github.io/blog/2017/compiling-R/

**Comment by fireballpoint1** [comment]
I found an easier hack of copying the binaries into /bin/local using sudo access. ~/bin as given in the documentation was a little confusing (Does it also try to tell the same thing btw )
