### ISSUE TITLE
invalid class “dgeMatrix” object: Not a valid 'Mnumeric' class object

### ISSUE THREAD

**Issue by fireballpoint1** [tdhock/PeakSegPipeline#6]
While running test-pipeline-demo.R 
I face the following error :```

```
Error in validObject(.Object) : 
  invalid class “dgeMatrix” object: Not a valid 'Mnumeric' class object
Calls: <Anonymous> ... Matrix -> new -> initialize -> initialize -> validObject
Execution halted
Error in system.or.stop(job.cmd) : non-zero exit code 1
```
Earlier I was facing the following error
```
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
```
Which I solved by installing package Matrix before running the Rscript.

Is there a similar hack for dgeMatrix error as well ?

**Comment by tdhock** [comment]
that is strange ... the Matrix package is supposed to be included with every installation of R .. where did your R come from?

about the dgeMatrix object I think it is defined in the Matrix package so installing Matrix should probably fix it too right?

**Comment by fireballpoint1** [comment]
As far as the inclusion of Matrix package as a default in R is concerned, I think the difference rose because I ran it as `Rscript testthat.R ` and unlike the R console, Rscript does not import the packages by default. 

for the dgeMatrix, I am myself bummed out as to why is this happening. Recently found an instance on the web where it worked fine with a depreciated version of the package Matrix. I will be trying that

**Comment by fireballpoint1** [comment]
Could someone with a successful run post the result of 
```
installed.packages()
```
